import { chromium } from 'playwright-core';
import { mkdirSync } from 'node:fs';
mkdirSync('shots/dark', { recursive: true });
const B = 'http://127.0.0.1:4173';
const browser = await chromium.launch({ headless: true, args: ['--no-sandbox', '--disable-dev-shm-usage', '--disable-gpu'] });
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, hasTouch: true, isMobile: true });
const p = await ctx.newPage();
const errs = [];
p.on('pageerror', e => errs.push(e.message));
const dark = () => p.evaluate(() => { document.documentElement.dataset.theme = 'dark'; document.documentElement.dataset.effective = 'dark'; });
await p.goto(B + '/');
await p.waitForTimeout(700);
await dark(); await p.waitForTimeout(500);
await p.screenshot({ path: 'shots/dark/d1-landing.png' });
await p.click('[data-act="demo"]');
await p.waitForSelector('.netcard', { timeout: 15000 });
await p.waitForTimeout(1100);
await dark(); await p.waitForTimeout(400);
await p.screenshot({ path: 'shots/dark/d2-home.png' });
await p.click('#tabAdd');
await p.waitForSelector('.who-grid');
await p.click('.who-grid .who');
await p.waitForSelector('.keypad2');
for (const k of ['3', '3', '0', '0']) await p.click(`.keypad2 .key2:text-is("${k}")`);
await p.waitForTimeout(300);
await dark(); await p.waitForTimeout(300);
await p.screenshot({ path: 'shots/dark/d3-compose.png' });
await p.click('.compose__top .iconbtn');
await p.waitForTimeout(500);
await p.goto(B + '/#/you');
await p.waitForSelector('.profile-head');
await p.waitForTimeout(700);
await dark(); await p.waitForTimeout(300);
await p.evaluate(() => { document.querySelector('#main').scrollTop = 600; });
await p.waitForTimeout(300);
await p.screenshot({ path: 'shots/dark/d4-you.png' });
console.log('errors:', errs.length, errs.slice(0, 3));
await browser.close();
