import { chromium } from 'playwright-core';
const b = await chromium.launch({ headless: true, args: ['--no-sandbox','--disable-dev-shm-usage'] });
const ctx = await b.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true });
const p = await ctx.newPage();
p.on('pageerror', e => console.log('PAGEERROR', e.message.slice(0,300)));
p.on('console', m => { if (m.type()==='error') console.log('CONSOLE', m.text().slice(0,300)); });
p.on('response', r => { if (r.url().includes('/api/')) console.log('API', r.status(), r.url().replace('http://127.0.0.1:4173','')); });
await p.goto('http://127.0.0.1:4173/', { waitUntil: 'domcontentloaded' });
await p.waitForSelector('.auth');
await p.click('[data-act="signup"]');
await p.waitForSelector('#su-name');
await p.fill('#su-name', 'Testy');
await p.fill('#su-pass', 'secret99');
await p.click('.sheet__foot .btn');
await p.waitForTimeout(3500);
console.log('HASH', await p.evaluate(() => location.hash));
console.log('BODY', await p.evaluate(() => document.querySelector('#bare')?.innerHTML.slice(0, 300) || document.querySelector('#main')?.innerHTML.slice(0,200)));
console.log('TOASTS', await p.evaluate(() => [...document.querySelectorAll('.toast')].map(t => t.textContent)));
await b.close();
